### ISSUE TITLE
Found version 4, expected 3

### ISSUE THREAD

**Issue by mjuri** [Sibiraj-S/ngx-editor#56]
Hi, I'm getting this issue:
ERROR in node_modules/ngx-editor/app/ngx-editor/ngx-editor-toolbar/ngx-editor-toolbar.component.d.ts (3,31): Cannot find module 'ngx-bootstrap'.
ERROR in Error: Metadata version mismatch for module /node_modules/ngx-editor/ngx-editor.d.ts, found version 4, expected 3

Maybe It's something easy to fix but i'm newbie using this tool. Any ideas?

**Comment by Sibiraj-S** [comment]
@mjuri. What version (both angular and ngx-editor) are you using and have u installed `ngx-bootstrap`.

**Comment by mjuri** [comment]
Hi! I'm using angular 1.4.10 and latest version of ngx-editor

**Comment by Sibiraj-S** [comment]
angular 1.4?

This Editor is for Angular 2.x, Works well with 4.x

**Comment by Sibiraj-S** [comment]
@mjuri . Close the issue if you are using angular 1.x

**Comment by mjuri** [comment]
sorry, my apologies, I gave you my angular cli version before. I'm using 4.2.4

**Comment by Sibiraj-S** [comment]
Try upgrading your angular version. The Editor works well with angular 5.2.0 which is a `peerDeendency`

**Comment by Sibiraj-S** [comment]
@mjuri . Did that work

**Comment by mjuri** [comment]
Yes, it was that. Thank so so much for your help I really appreciate it

**Comment by Sibiraj-S** [comment]
😄
