### ISSUE TITLE
[Bug]: Problem with @types/prosemirror-model after upgrading Angular from 13.3.0 to 13.3.5

### ISSUE THREAD

**Issue by VBobCat** [sibiraj-s/ngx-editor#400]
### What happened?

After upgrading Angular from 13.3.0 to 13.3.5, application is breaking at `ng serve` with two ocurrences of this error:
```
error TS2709: Cannot use namespace 'OrderedMap' as a type
```

### Version

v12.4.0

### Angular Version

v13.3.5

### Relevant log output

```shell
Error: node_modules/@types/prosemirror-model/index.d.ts:1147:40 - error TS2709: Cannot use namespace 'OrderedMap' as a type.

1147     nodes: { [name in N]: NodeSpec } | OrderedMap<NodeSpec>;
                                            ~~~~~~~~~~


Error: node_modules/@types/prosemirror-model/index.d.ts:1154:41 - error TS2709: Cannot use namespace 'OrderedMap' as a type.

1154     marks?: { [name in M]: MarkSpec } | OrderedMap<MarkSpec> | null | undefined;
                                             ~~~~~~~~~~
```

**Comment by sibiraj-s** [comment]
Can you try v12.4.1. I have pinned all the prosemirror definitely typed packages. Looks someone broke something on recent releases.

**Comment by VBobCat** [comment]
Hello, @sibiraj-s ! Thank you so much, it worked! But only after I ran ng new in a new folder, installed all my dependencies anew with npm (including ngx-editor) and and copied my src files to it.
Your package is fantastic and I was worried with having to replace it.

**Comment by sibiraj-s** [comment]
Glad that worked 🎉
